# Generated by Django 4.2.2 on 2023-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_producto'),
        ('carrito', '0003_itemcarrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(to='Menu.producto'),
        ),
    ]
