# Generated by Django 4.2.2 on 2023-07-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0003_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='whatsapp',
            new_name='foto',
        ),
    ]
