# Generated by Django 4.2.2 on 2023-07-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0004_rename_whatsapp_galeria_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
