# Generated by Django 4.2.2 on 2023-10-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0006_delete_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
