# Generated by Django 4.2.2 on 2023-08-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_categoria_producto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
