# Generated by Django 4.2.2 on 2023-09-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0008_alter_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
